direction: right 

vars: {
  toolName: "Hefe"
}


hefe: ${toolName} tool architecture

hefe.odin: Odin - ADS scenario enhancement
hefe.odin.llm: LLM interface
hefe.odin.prompts: Prompt templates {
  shape: cylinder
}
hefe.odin.llm <-> hefe.odin.prompts: Use existing scenarios for prompts


hefe.thor: Thor - ADS scenario execution
hefe.thor.carla: Carla - ADS simulator
hefe.loki.testCaseRepos: ADS scenario repositories {
  shape: cylinder
}
# Add rabbitMQ to Thor
hefe.thor.rabbitMQ: RabbitMQ - Message broker

hefe.loki: Loki - ADS scenario orchestration
userInteraction: Human {
  shape: person
}
userInteraction -> hefe.loki: User interaction with ${toolName}


hefe.loki -> hefe.odin: Enhance raw scenario
hefe.odin -> hefe.thor: Enhanced scenario
hefe.thor -> hefe.loki: Execution results
hefe.loki -> hefe.thor: Execute raw scenario
hefe.loki -> userInteraction: Result evaluation

llm: LLMs {
  shape: cloud
}

llm <-> hefe.odin.llm: Remote LLM APIs