name: Build
on: [push, workflow_dispatch]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile essay
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          working_directory: ./essay
          args: -pdf -g -bibtex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -latexoption=-shell-escape
      - name: Upload essay artifact
        uses: actions/upload-artifact@v4
        with:
          name: essay
          path: ./essay/main.pdf
