# Lånt fra https://github.com/jdujava/TeXtured/blob/master/.github/workflows/main.yml
name: CI

env:
  THESIS_FOLDER: .

on:
  push:
    branches: [main]
    paths:
      - "./**"
  workflow_dispatch:

jobs:
  ## thanks to https://github.com/exaexa/better-mff-thesis
  ##       and https://github.com/mff-cuni-cz/cuni-thesis-validator
  build:
    name: Build PDF and upload as an artifact
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: ${{ env.THESIS_FOLDER }}
          root_file: thesis.tex
          latexmk_shell_escape: true
          texlive_version: latest # must be `2024` or later (`latest` chosen by default)
          extra_system_packages: coreutils icu inkscape # `coreutils` for `mktemp`, `icu` for `uconv`
      - name: Install poppler-utils for pdfinfo
        run: sudo apt-get update && sudo apt-get install -y poppler-utils
      - name: Get the page count of the thesis and add it to the README.md
        run: |
          # Get the page count of the thesis
          PAGE_COUNT=$(pdfinfo ${{ env.THESIS_FOLDER }}/thesis.pdf | grep Pages | awk '{print $2}')
          PERCENTAGE=$(echo "scale=2; $PAGE_COUNT / 100 * 100" | bc)
          # Add the page count to the README.md
          echo "<br/><br/>The thesis currently has $PAGE_COUNT / 100 pages, which is
          $PERCENTAGE percent." >> README.md
      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.THESIS_FOLDER }}
          path: |
            README.md
            ${{ env.THESIS_FOLDER }}/thesis.pdf
  verify:
    name: Verify PDF/A
    runs-on: ubuntu-latest
    needs: build
    container: { image: ghcr.io/jdujava/cuni-thesis-validator }
    steps:
      - name: Get the PDF file from the artifact
        uses: actions/download-artifact@v4
      - name: Verify the PDF file with VeraPDF
        # TODO: Deal med dobbel `$FOLDER` i pathen lol
        run: verify ${{ env.THESIS_FOLDER }}/${{ env.THESIS_FOLDER }}/thesis.pdf | tee /dev/stderr | grep -qE 'nonCompliant="0" failedJobs="0"'

  ## inspired by https://github.com/Pseudomanifold/latex-mimosis
  deploy:
    name: Deploy latest build of PDF and README.md to gh-pages branch
    if: github.event_name == 'push' # only deploy on push
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Get the PDF and README.md from the artifact
        uses: actions/download-artifact@v4
      - name: Commit and push the PDF and README.md to `gh-pages` branch
        run: |
          cd ${{ env.THESIS_FOLDER }}
          git init -b temp
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git add .
          git commit -m "[CI] Update to latest PDF and README.md"
          git push --force origin temp:gh-pages
